#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

CONF='realm'
PROG='/usr/bin/realm'

start_service() {
	local enabled config_file

	config_load "$CONF"
	config_get_bool enabled 'config' 'enabled' '0'
	[ "$enabled" -eq 1 ] || return 0

	config_get config_file 'config' 'config_file' '/etc/realm/config.toml'
	if [ ! -f "$config_file" ]; then
		logger -p daemon.err -t realm "config file not found: $config_file"
		return 1
	fi

	procd_open_instance
	procd_set_param command "$PROG" -c "$config_file"
	procd_set_param file "$config_file"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
